#!/usr/bin/env bun

/**
 * PreToolUse hook: Prevent duplicate issue-guidance patterns.
 *
 * Blocks Edit/Write tool calls that would introduce inline "file an issue on target repo"
 * patterns instead of using the canonical buildIssueGuidance() helper from hook-utils.ts.
 *
 * This enforces the consolidation established by buildIssueGuidance() and prevents
 * patterns from being duplicated across multiple hooks.
 *
 * Dual-mode: exports a SwizHook for inline dispatch and remains
 * executable as a standalone script for backwards compatibility and testing.
 */

import {
  preToolUseAllow,
  preToolUseDeny,
  runSwizHookAsMain,
  type SwizHook,
} from "../src/SwizHook.ts"
import { isFileEditTool } from "../src/tool-matchers.ts"
import type { FileEditHookInput } from "./schemas.ts"

/**
 * Patterns that indicate inline issue-guidance text that should use buildIssueGuidance().
 * These patterns suggest the developer is inlining guidance instead of calling the helper.
 */
const PROBLEMATIC_PATTERNS = [
  // "file an issue on target repo" phrasing
  /file\s+an\s+issue\s+(?:on\s+)?(?:the\s+)?(?:target|external)\s+repo/gi,

  // "gh issue create --repo" with specific repo (not placeholder)
  /gh\s+issue\s+create\s+--repo\s+[a-z0-9_-]+\/[a-z0-9_-]+/gi,

  // Cross-repo issue guidance phrasing
  /consider\s+filing\s+an\s+issue\s+(?:on\s+)?(?:the\s+)?target\s+repo/gi,

  // "file a GitHub issue on X" variant
  /file\s+a?\s+GitHub\s+issue\s+on\s+(?:[a-z0-9_-]+\/[a-z0-9_-]+|that\s+repo)/gi,

  // "file them as GitHub issues" variant
  /file\s+them\s+as\s+GitHub\s+issues/gi,

  // Hardcoded "gh issue create --title" command (without --repo placeholder)
  /gh\s+issue\s+create\s+--title\s+"[^"]+"\s+--body/gi,
]

const pretooluseSandboxGuidanceConsolidation: SwizHook<FileEditHookInput> = {
  name: "pretooluse-sandbox-guidance-consolidation",
  event: "preToolUse",
  matcher: "Edit|Write",
  timeout: 5,

  run(rawInput) {
    const input = rawInput as FileEditHookInput

    // Only check Edit and Write tools
    if (!isFileEditTool(input.tool_name ?? "")) return {}

    // Skip validation for hook files that by design contain issue-guidance patterns
    const filePath = input.tool_input?.file_path
    if (
      filePath?.includes("pretooluse-sandbox-guidance-consolidation") ||
      filePath?.includes("stop-todo-tracker") ||
      filePath?.includes("stop-auto-continue")
    ) {
      return {}
    }

    // NFKC normalize before pattern matching
    const newContent: string = (input.tool_input?.new_string ?? "").normalize("NFKC")
    if (!newContent) return {}

    // Check if new content contains problematic patterns
    for (const pattern of PROBLEMATIC_PATTERNS) {
      if (pattern.test(newContent)) {
        const matches = newContent.match(pattern)
        const matchText = matches?.[0] ?? "pattern match"

        return preToolUseDeny(
          [
            "Inline issue-guidance pattern detected — use buildIssueGuidance() instead.",
            "",
            `  Found: "${matchText}"`,
            "",
            "This text should be generated by buildIssueGuidance() in hooks/hook-utils.ts",
            "to keep issue-guidance messages consistent and centralized.",
            "",
            "Consolidation reference:",
            "  buildIssueGuidance(repo: string | null, options?: { crossRepo?: boolean; hostname?: string }): string",
            "",
            "Usage example:",
            '  const guidance = buildIssueGuidance("owner/repo", { crossRepo: true, hostname: "github.com" })',
            "  const message = `If this change is needed, consider filing an issue there.\\n${guidance}`",
            "",
            "Benefits of consolidation:",
            "  • Consistent messaging across all sandbox enforcement hooks",
            "  • Single source of truth for issue-guidance text",
            "  • Easier to update guidance without touching multiple files",
            "  • Prevents duplicate patterns from reappearing",
          ].join("\n")
        )
      }
    }

    return preToolUseAllow("No inline issue-guidance patterns detected")
  },
}

export default pretooluseSandboxGuidanceConsolidation

// ─── Standalone execution (file-based dispatch / manual testing) ────────────
if (import.meta.main) await runSwizHookAsMain(pretooluseSandboxGuidanceConsolidation)
