#!/usr/bin/env bun
/**
 * PreToolUse hook: Block direct edits to lockfiles.
 *
 * Dual-mode: exports a SwizFileEditHook for inline dispatch and remains
 * executable as a standalone script for backwards compatibility and testing.
 */

import {
  preToolUseAllow,
  preToolUseDeny,
  runSwizHookAsMain,
  type SwizFileEditHook,
} from "../src/SwizHook.ts"
import type { FileEditHookInput } from "./schemas.ts"

const LOCKFILE_RE =
  /(^|[\\/])(pnpm-lock\.yaml|package-lock\.json|npm-shrinkwrap\.json|yarn\.lock|bun\.lockb?|shrinkwrap\.yaml)$/i

const LOCKFILE_REASON = [
  "You cannot edit lockfiles directly.",
  "",
  "Lockfiles (pnpm-lock.yaml, package-lock.json, yarn.lock, bun.lock, etc.) are",
  "machine-generated by the package manager. Any manual edit will be overwritten",
  "the next time dependencies are installed or updated, and can silently corrupt",
  "the dependency graph.",
  "",
  "To update a lockfile, run the appropriate package manager command instead:",
  "  bun install          # bun.lock / bun.lockb",
  "  pnpm install         # pnpm-lock.yaml",
  "  npm install          # package-lock.json / npm-shrinkwrap.json",
  "  yarn install         # yarn.lock",
  "",
  "Do not edit lockfiles directly.",
].join("\n")

function evaluate(input: FileEditHookInput) {
  const filePath = input.tool_input?.file_path ?? ""
  if (LOCKFILE_RE.test(filePath)) return preToolUseDeny(LOCKFILE_REASON)
  return preToolUseAllow(`File is not a lockfile: ${filePath.split("/").pop()}`)
}

const pretoolusNoLockfileEdit: SwizFileEditHook = {
  name: "pretooluse-no-lockfile-edit",
  event: "preToolUse",
  matcher: "Edit|Write|NotebookEdit",
  timeout: 5,

  run(input) {
    return evaluate(input)
  },
}

export default pretoolusNoLockfileEdit

// ─── Standalone execution (file-based dispatch / manual testing) ────────────
if (import.meta.main) await runSwizHookAsMain(pretoolusNoLockfileEdit)
