#!/usr/bin/env bun

/**
 * PreToolUse hook: Prevent duplicate issue-guidance patterns.
 *
 * Blocks Edit/Write tool calls that would introduce inline "file an issue on target repo"
 * patterns instead of using the canonical buildIssueGuidance() helper from hook-utils.ts.
 *
 * This enforces the consolidation established by buildIssueGuidance() and prevents
 * patterns from being duplicated across multiple hooks.
 */

import { allowPreToolUse, denyPreToolUse, isFileEditTool } from "../src/utils/hook-utils.ts"
import { fileEditHookInputSchema } from "./schemas.ts"

const input = fileEditHookInputSchema.parse(await Bun.stdin.json())

// Only check Edit and Write tools
if (!isFileEditTool(input.tool_name ?? "")) {
  process.exit(0)
}

// Skip validation for hook files that by design contain issue-guidance patterns
const filePath = input.tool_input?.file_path
if (
  filePath?.includes("pretooluse-sandbox-guidance-consolidation") ||
  filePath?.includes("stop-todo-tracker") ||
  filePath?.includes("stop-auto-continue")
) {
  process.exit(0)
}

// NFKC normalization handled by fileEditHookInputSchema.transform()
const newContent: string = input.tool_input?.new_string ?? ""
if (!newContent) {
  process.exit(0)
}

/**
 * Patterns that indicate inline issue-guidance text that should use buildIssueGuidance().
 * These patterns suggest the developer is inlining guidance instead of calling the helper.
 */
const PROBLEMATIC_PATTERNS = [
  // "file an issue on target repo" phrasing
  /file\s+an\s+issue\s+(?:on\s+)?(?:the\s+)?(?:target|external)\s+repo/gi,

  // "gh issue create --repo" with specific repo (not placeholder)
  /gh\s+issue\s+create\s+--repo\s+[a-z0-9_-]+\/[a-z0-9_-]+/gi,

  // Cross-repo issue guidance phrasing
  /consider\s+filing\s+an\s+issue\s+(?:on\s+)?(?:the\s+)?target\s+repo/gi,

  // "file a GitHub issue on X" variant
  /file\s+a?\s+GitHub\s+issue\s+on\s+(?:[a-z0-9_-]+\/[a-z0-9_-]+|that\s+repo)/gi,

  // "file them as GitHub issues" variant
  /file\s+them\s+as\s+GitHub\s+issues/gi,

  // Hardcoded "gh issue create --title" command (without --repo placeholder)
  /gh\s+issue\s+create\s+--title\s+"[^"]+"\s+--body/gi,
]

// Check if new content contains problematic patterns
for (const pattern of PROBLEMATIC_PATTERNS) {
  if (pattern.test(newContent)) {
    const matches = newContent.match(pattern)
    const matchText = matches?.[0] ?? "pattern match"

    denyPreToolUse(
      [
        "Inline issue-guidance pattern detected — use buildIssueGuidance() instead.",
        "",
        `  Found: "${matchText}"`,
        "",
        "This text should be generated by buildIssueGuidance() in hooks/hook-utils.ts",
        "to keep issue-guidance messages consistent and centralized.",
        "",
        "Consolidation reference:",
        "  buildIssueGuidance(repo: string | null, options?: { crossRepo?: boolean; hostname?: string }): string",
        "",
        "Usage example:",
        '  const guidance = buildIssueGuidance("owner/repo", { crossRepo: true, hostname: "github.com" })',
        "  const message = `If this change is needed, consider filing an issue there.\\n${guidance}`",
        "",
        "Benefits of consolidation:",
        "  • Consistent messaging across all sandbox enforcement hooks",
        "  • Single source of truth for issue-guidance text",
        "  • Easier to update guidance without touching multiple files",
        "  • Prevents duplicate patterns from reappearing",
      ].join("\n")
    )
  }
}

allowPreToolUse("No inline issue-guidance patterns detected")
