#!/usr/bin/env bun

import { filePathGuardHook } from "./utils/hook-utils.ts"

// Matches any lockfile at path boundaries (handles / and \ separators, case-insensitive)
const LOCKFILE_RE =
  /(^|[\\/])(pnpm-lock\.yaml|package-lock\.json|npm-shrinkwrap\.json|yarn\.lock|bun\.lockb?|shrinkwrap\.yaml)$/i

const LOCKFILE_REASON = [
  "You cannot edit lockfiles directly.",
  "",
  "Lockfiles (pnpm-lock.yaml, package-lock.json, yarn.lock, bun.lock, etc.) are",
  "machine-generated by the package manager. Any manual edit will be overwritten",
  "the next time dependencies are installed or updated, and can silently corrupt",
  "the dependency graph.",
  "",
  "To update a lockfile, run the appropriate package manager command instead:",
  "  bun install          # bun.lock / bun.lockb",
  "  pnpm install         # pnpm-lock.yaml",
  "  npm install          # package-lock.json / npm-shrinkwrap.json",
  "  yarn install         # yarn.lock",
  "",
  "Do not edit lockfiles directly.",
].join("\n")

const main = filePathGuardHook((fp) => LOCKFILE_RE.test(fp), LOCKFILE_REASON)

if (import.meta.main) {
  main().catch((e) => {
    console.error("Hook error:", e)
    process.exit(1)
  })
}
