#!/usr/bin/env bun

/**
 * PreToolUse hook: Prevent duplicate issue-guidance patterns.
 *
 * Blocks Edit/Write tool calls that would introduce inline "file an issue on target repo"
 * patterns instead of using the canonical buildIssueGuidance() helper from hook-utils.ts.
 *
 * This enforces the consolidation established by buildIssueGuidance() and prevents
 * patterns from being duplicated across multiple hooks.
 *
 * Dual-mode: exports a SwizHook for inline dispatch and remains
 * executable as a standalone script for backwards compatibility and testing.
 */

import {
  preToolUseAllow,
  preToolUseDeny,
  runSwizHookAsMain,
  type SwizHook,
  type SwizHookOutput,
} from "../src/SwizHook.ts"
import type { FileEditHookInput } from "../src/schemas.ts"
import { isFileEditTool } from "../src/tool-matchers.ts"

/**
 * Patterns that indicate inline issue-guidance text that should use buildIssueGuidance().
 * These patterns suggest the developer is inlining guidance instead of calling the helper.
 */
const PROBLEMATIC_PATTERNS = [
  // "file an issue on target repo" phrasing
  /file\s+an\s+issue\s+(?:on\s+)?(?:the\s+)?(?:target|external)\s+repo/gi,

  // "gh issue create --repo" with specific repo (not placeholder)
  /gh\s+issue\s+create\s+--repo\s+[a-z0-9_-]+\/[a-z0-9_-]+/gi,

  // Cross-repo issue guidance phrasing
  /consider\s+filing\s+an\s+issue\s+(?:on\s+)?(?:the\s+)?target\s+repo/gi,

  // "file a GitHub issue on X" variant
  /file\s+a?\s+GitHub\s+issue\s+on\s+(?:[a-z0-9_-]+\/[a-z0-9_-]+|that\s+repo)/gi,

  // "file them as GitHub issues" variant
  /file\s+them\s+as\s+GitHub\s+issues/gi,

  // Hardcoded "gh issue create --title" command (without --repo placeholder)
  /gh\s+issue\s+create\s+--title\s+"[^"]+"\s+--body/gi,
]

function isGuidanceExemptPath(filePath: string): boolean {
  return [
    "pretooluse-sandbox-guidance-consolidation",
    "stop-todo-tracker",
    "stop-auto-continue",
  ].some((fragment) => filePath.includes(fragment))
}

function guidanceConsolidationDenial() {
  return preToolUseDeny(
    [
      "You are duplicating issue-guidance copy instead of using the canonical helper.",
      "",
      "This text should be generated by buildIssueGuidance() in hooks/hook-utils.ts",
      "to keep issue-guidance messages consistent and centralized.",
      "",
      "Consolidation reference:",
      "  buildIssueGuidance(repo: string | null, options?: { crossRepo?: boolean; hostname?: string }): string",
      "",
      "Usage example:",
      '  const guidance = buildIssueGuidance("owner/repo", { crossRepo: true, hostname: "github.com" })',
      "  const message = `If this change is needed, consider filing an issue there.\\n${guidance}`",
      "",
      "Benefits of consolidation:",
      "  • Consistent messaging across all sandbox enforcement hooks",
      "  • Single source of truth for issue-guidance text",
      "  • Easier to update guidance without touching multiple files",
      "  • Prevents duplicate patterns from reappearing",
    ].join("\n")
  )
}

export function evaluateSandboxGuidanceConsolidation(input: FileEditHookInput): SwizHookOutput {
  if (!isFileEditTool(input.tool_name ?? "")) return {}
  const filePath = input.tool_input?.file_path ?? ""
  if (isGuidanceExemptPath(filePath)) return {}

  const newContent = (input.tool_input?.new_string ?? "").normalize("NFKC")
  if (!newContent) return {}
  return PROBLEMATIC_PATTERNS.some((pattern) => pattern.test(newContent))
    ? guidanceConsolidationDenial()
    : preToolUseAllow("Continue in canonical issue-guidance mode.")
}

const pretooluseSandboxGuidanceConsolidation: SwizHook<FileEditHookInput> = {
  name: "pretooluse-sandbox-guidance-consolidation",
  event: "preToolUse",
  matcher: "Edit|Write",
  timeout: 5,

  run(rawInput) {
    return evaluateSandboxGuidanceConsolidation(rawInput as FileEditHookInput)
  },
}

export default pretooluseSandboxGuidanceConsolidation

// ─── Standalone execution (file-based dispatch / manual testing) ────────────
if (import.meta.main) await runSwizHookAsMain(pretooluseSandboxGuidanceConsolidation)
